version: "3.9"

services:
  manager-api:
     container_name: manager-api
     image: stianlaa/dev-docker-repo:manager-api_${NU_VER}
     build:
       context: .
       dockerfile: manager-api/Dockerfile
     entrypoint: [ "./run-service" ]
     environment:
       - NU_VER=image_v0.0.5
     ports:
       - "8000:8000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  arg-poc:
    container_name: arg-poc
    image: stianlaa/dev-docker-repo:arg-poc_${NU_VER}
    build:
      context: .
      dockerfile: arg-poc/Dockerfile
    # Example of how container parameters can be defined here
    entrypoint: [ "./run-service",
                  "test1", "value1",
                  "test2", "value2"
    ]

  network-poc:
    container_name: network-poc
    image: stianlaa/dev-docker-repo:network-poc_${NU_VER}
    build:
      context: .
      dockerfile: network-poc/Dockerfile
    # Example of how start dependency can be added
    depends_on:
      - arg-poc
    entrypoint: [ "./run-service" ]
    ports:
      - "8000:8000"

  volume-poc:
    container_name: volume-poc
    image: stianlaa/dev-docker-repo:volume-poc_${NU_VER}
    build:
      context: .
      dockerfile: volume-poc/Dockerfile
    entrypoint: [ "./run-service" ]

  panic-poc:
    container_name: panic-poc
    image: stianlaa/dev-docker-repo:panic-poc_${NU_VER}
    build:
      context: .
      dockerfile: panic-poc/Dockerfile
    entrypoint: [ "./run-service" ]
    # Various restart configurations available
    restart: on-failure
    # restart: no
