version: "3.9"

services:
  first-app:
    image: stianlaa/dev-docker-repo:first-tag
    container_name: first-app-container
## Entrypoint alternative 1:
#    entrypoint:
#      - ./run-service
#      - test1
#      - test2
#      - test3
#      - test4

## Entrypoint alternative 2:
#    entrypoint: ["./run-service", "compose-entrypoint-param-1", "compose-entrypoint-param-2"]

## Entrypoint alternative 3:
    entrypoint: ["./run-service",
      "test1", "test2",
      "test3", "test4"
    ]


#  second-app:
#    image: stianlaa/dev-docker-repo:second-tag
#    container_name: second-app-container