version: "3.9"

services:
  arg-poc:
    container_name: arg-poc-container
    image: stianlaa/dev-docker-repo:first-tag
    build:
      context: .
      dockerfile: arg-poc/Dockerfile
    # Example of how container parameters can be defined here
    entrypoint: [ "./run-service",
                  "test1", "value1",
                  "test2", "value2"
    ]

  network-poc:
    container_name: network-poc-container
    image: stianlaa/dev-docker-repo:second-tag
    build:
      context: .
      dockerfile: network-poc/Dockerfile
    # Example of how start dependency can be added
    depends_on:
      - arg-poc
    entrypoint: [ "./run-service" ]
    ports:
      - "8000:8000"

  volume-poc:
    container_name: volume-poc-container
    image: stianlaa/dev-docker-repo:third-tag
    build:
      context: .
      dockerfile: volume-poc/Dockerfile
    entrypoint: [ "./run-service" ]

  panic-poc:
    container_name: panic-poc-container
    image: stianlaa/dev-docker-repo:fourth-tag
    build:
      context: .
      dockerfile: panic-poc/Dockerfile
    entrypoint: [ "./run-service" ]
    # Various restart configurations available
    restart: on-failure
    # restart: no
