version: "3.9"

services:
  first-app:
    container_name: first-app-container
    image: stianlaa/dev-docker-repo:first-tag
    build:
      context: .
      dockerfile: ./first-app/Dockerfile
    # Container parameters can be defined here
    entrypoint: ["./run-service",
      "test1", "value1",
      "test2", "value2"
    ]

  second-app:
    container_name: second-app-container
    image: stianlaa/dev-docker-repo:second-tag
    build:
      context: .
      dockerfile: ./second-app/Dockerfile
    # Example of how start dependency can be added
    depends_on:
      - first-app
    entrypoint: ["./run-service",
      "test3", "value3",
      "test4", "value4"
    ]
